### ISSUE TITLE
gRPC - Support for search with gRPC in `QdrantClient`

### ISSUE THREAD

**Issue by monatis** [qdrant/qdrant_client#37]
Methods will be refactored individually to support API calls over REST and gRPC clients uniformly. This issue is for refactoring of `QdrantClient.search` method --open separate issues if you are planning to apply the same refactoring to other methods.

## Tasks
- [ ] Define a union over objects from pydantic models and gRPC request objects in the method signature.
- [ ] If type of the object specified is not compatible with the preferred client, handle conversion internally.
- [ ] If it is not possible to get a dict from pydantic model and initialize a gRPC request object from it, implement a utility function for conversion.
- [ ]
